---
- include:              '../tasks/user_groups.yml'
- include:              '../tasks/users.yml'
- include:              '../tasks/authorized_keys.yml'
- include:              '../tasks/allow_users.yml'
