---
- include_tasks:        '../tasks/install_packages.yml'
- include_tasks:        '../tasks/user_groups.yml'
- include_tasks:        '../tasks/users.yml'
- include_tasks:        '../tasks/authorized_keys.yml'
  vars:
    authorized_keys:
      - user:             'readonly'
        keyfile:          "../../inventory/hosts/{{ item }}/users/root/files/ssh_keys/id_rsa.pub"
  with_items:
    - "{{ groups['sshfs-client'] }}"
    - "{{ groups['remote'] }}"
- include_tasks:        '../tasks/allow_users.yml'
- include_tasks:        '../tasks/create_files.yml'
- include_tasks:        '../tasks/install_files.yml'
- include_tasks:        '../tasks/template_files.yml'
- include_tasks:        '../tasks/symlinks.yml'
- include_tasks:        '../tasks/restart_services.yml'
  when:                 template_files_result.changed
                        or symlinks_result.changed
